[features]
seeds = false
skip-lint = false
[programs.localnet]
morra_lotto = "8ce52PpcApfmiNVX45tFrudt9kHYJQXSJuC8ZzxUxhMo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/raider/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
